### ISSUE TITLE
Error on RasPi3 B+ cluster

### ISSUE THREAD

**Issue by mnakao** [AdamSimpson/SPH#11]
Dear developers,

I try to run your SPH in our RasPi3 B+ cluster. OS is the lastest Raspbian, version number is 9.4 (/etc/debian_version). 

But when executing it, the following error occurs.

> $ mpirun -np 2 ./bin/sph.out
> compute rank: 0, num compute procs: 1
> libEGL warning: DRI2: failed to authenticate
> sph.out: egl_utils.c:171: init_ogl: Assertion `state->surface != EGL_NO_SURFACE` failed.

Do you know the cause of the error?

Thanks,

**Comment by mnakao** [comment]
I solved this issue myself.

I create new symbolic links.

> sudo ln -sf /opt/minecraft-pi/lib/brcm/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so
> sudo ln -sf /opt/minecraft-pi/lib/brcm/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1
> sudo ln -sf /opt/minecraft-pi/lib/brcm/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so
> sudo ln -sf /opt/minecraft-pi/lib/brcm/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2

Moreover, I run above directory.
>  mpirun -np 2 ./SPH/bin/sph.out

It's successful !

**Comment by rockangator** [comment]
I tried this. The make command ended with a couple warnings. The make run command gave no errors but some values and i didnot get and visual of ball or anything. Same with the bare mpirun command as yours...attaching the result...pls tell if i am doing sth wrong.
![Capture](https://user-images.githubusercontent.com/32011655/77227396-176d3e80-6ba6-11ea-91df-e759235f7fb9.PNG)

**Comment by rockangator** [comment]
@mnakao does this seem similar to you? Did you faace something like this?

**Comment by mnakao** [comment]
@rockangator Sorry. I encountered this problem more than a year ago and have forgotten it. The environment at that time was also dismantled, so it can not be reproduced.

**Comment by rockangator** [comment]
@mnakao alright i understand. But were you able to successfully satisfactorily run the project as intended with the visuals and all?
And did you get stuck here?
I was told this could be bcz the project originally was made for the OG Rpi and not the newer versions but i see you tried this on a new rpi3b+ cluster.
Could you guide me? How i could solve this...?

**Comment by mnakao** [comment]
@rockangator I can run the SPH project in our RasPi3 B+ cluster perfectly. However, I can't remember more. There were no notes left.
